USE [MMApp]
GO

/****** Object:  Table [dbo].[Books_Currency]    Script Date: 2018/07/20 8:35:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Books_Currency](
	[Id] [int] NOT NULL,
	[CurrencyName] [varchar](50) NOT NULL,
	[CurrencySymbol] [varchar](5) NOT NULL,
 CONSTRAINT [PK_Books_Currency] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


