USE [MMApp]
GO

/****** Object:  Table [dbo].[Books_Format]    Script Date: 2018/07/20 7:26:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Books_Format](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FormatName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Books_BookFormat] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


